# Generated by Django 4.0.3 on 2022-04-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(choices=[('Lyuks', 'Lyuks'), ('Biznes', 'Biznes'), ('Kvartera', 'Kvartera')], max_length=100)),
                ('type_of_booking', models.CharField(choices=[('Kunlik band qilish', 'Kunlik'), ('Soatlik band qilish', 'Soatlik')], max_length=100)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploadRoom')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
